server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/peppermint100/workspace/git-local-repo
          uri: https://github.com/peppermint100/spring-cloud-config
#          username:
#          password: